services:
  app:
    build: ./app
    container_name: app_server
    networks:
     - napat_internet
    volumes: 
     - ./app:/app
    ports:
     - "5000:5000"
    depends_on:
     sql:
      condition: service_healthy 

  sql: 
    build: ./sql
    container_name: db_server
    ports:
     - "3307:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=rootpassword
    networks:
     - napat_internet
    healthcheck:
     test: ["CMD", "mysqladmin","ping","-uroot","-prootpassword"]
     interval: 30s
     timeout: 10s
     retries: 3

networks:
  napat_internet:
   driver: bridge
